### ISSUE TITLE
Make thumb size configurable

### ISSUE THREAD

**Issue by fballiano** [fballiano/openmage-image-cleaner#10]
as requested in https://github.com/fballiano/magento1-image-cleaner/issues/3

**Comment by addison74** [comment]
Good improvement but this time I will do the change directly into the code. One less entry in the config_data table and one relief in case of uninstallation. 

PS - If you get some time please revise your commit in OpenMage related to reviews. There is a strange behavior when deleting reviews and we talked about this in a post.

**Comment by fballiano** [comment]
I know, I didn't want to have a configuration mask.. but I'm for sure adding a "directory blacklist" for wysiwyg subfolders so...

BTW you could change the default via XML ;-)
