### ISSUE TITLE
Center ID column

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#11]
I did a small change to center the ID column. It looks better now, because Entity Type is centered too.

/app/code/community/Fballiano/ImageCleaner/Block/Adminhtml/Fbimagecleaner/Grid.php

```
    protected function _prepareColumns()
    {
        $this->addColumn('image_id', array(
            'header' => $this->__('ID'),
            'type' => 'text',
            'width' => '100px',
            'align'=> 'center',
            'index' => 'image_id'
        ));

```

**Comment by fballiano** [comment]
Ad fas as I know the ID column is never centered, I've checked multiple places in the core, most of the times it's right aligned (which I think it's the right choice for numbers) but sometimes it's left aligned (who know why), so I aligned it right.

I know, it's a mix and match but I'd go for uniformity and for the "correct" alignment for the data that's been shown :-)
