### ISSUE TITLE
Open image in a new window

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#14]
Now that we have more configuration options in Backend by adding the size of the image and the blacklist, I propose to add another option, whether clicking on the image opens or not in a new window.

Basically we add a new option in /etc/system.xml and change the code in /Block/Adminhtml/Fbimagecleaner/Renderer/image.php to line 41.

```
return "<a href='{$url}{$row->getPath()}' target='_blank'><img src='{$url}{$row->getPath()}' style='max-width:{$max_width}px' /></a>";
```

**Comment by addison74** [comment]
... or we can extend the Actions column with a new link:

Open | Download | Delete

**Comment by fballiano** [comment]
I think it's uncomfortable to open it in the same window, but anyway at the moment I added the configuration and modified the template, still didn't add a separate action cause it's way easier for people to click on the image rather than a link, which is way smaller and sometimes may be misaligned if compared to the image ;-)

**Comment by addison74** [comment]
My suggestion wasn't about opening the image in the same window which is really annoying. It is exactly the same behavior as before with the request of enable/disable this feature or make it visible as an Actions.

**Comment by addison74** [comment]
Based on a configuration value Yes/Now will add/delete that <a> tag for the image. It is disabling the click on the image.

**Comment by fballiano** [comment]
done, enabled by default

**Comment by addison74** [comment]
Once you implemented this feature I would remove the code related to ```<how_to_open_image>new</how_to_open_image>```.  It is no longer relevant and the implementation resulted from a misunderstanding of the request.

When the link is activated it should always open the image in a new window. As I said, it's annoying to open it in the same window.

**Comment by fballiano** [comment]
better, all done already
