### ISSUE TITLE
New feature cleaning up /media/tmp directory

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#15]
When someone uploads an image first time it goes to /media/tmp/catalog/product directory. After pressing the [Save] button the file goes to /media/catalog/product directory then it is deleted from /tmp. Over the time there are still a lot of files in /media/tmp without any reason. What about including this directory in our clean up process? By filtering on a column we can get where is the file stored. 

I did not check if for categories is the same pattern like for products (e.g. /media/tmp/catalog/category).

**Comment by fballiano** [comment]
well, I think we could simply add a button to delete the whole "media/tmp" folder, there's nothing that should be kept in there...

**Comment by addison74** [comment]
I agree. It is only a temporary area and what has been uploaded here is assumed to already exist locally or on the server. I am waiting for you with an implementation proposal when you have some time.

**Comment by fballiano** [comment]
Functionality was added in the 0.7.0 release ;-) let me know!

**Comment by addison74** [comment]
Excellent. I appreciate you fast reaction. I will test it and come back with a feedback. Have a lovely weekend.

**Comment by addison74** [comment]
After testing the new addition I did not find any issues, it works as expected. Between us this extension should be integrated in OpenMage. Deconf ImaClean is far behind as features and for years it was the only option.

**Comment by fballiano** [comment]
thanks! :-) that's nice to know
