### ISSUE TITLE
Orphan images after importing process

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#18]
If you import a CSV file to create/update products and if this file contains columns related to images like _media_attribute_id, _media_image, _media_lable, _media_position, _media_is_disabled then you have to place the images in **/media/import** directory. 

After the import process is done successfully the files from /media/import go to /media/catalog/product but they are not deleted from the initial location remaining there as orphans.

Please take this in consideration as a new feature to your extension.

**Comment by fballiano** [comment]
added a "flush media/import" button in 0.8.0 ;-)

**Comment by addison74** [comment]
Excellent work.
