### ISSUE TITLE
SQL Constraint vialoation when 2 images with same name but different capitalization are present

### ISSUE THREAD

**Issue by tobihille** [fballiano/openmage-image-cleaner#21]
First: thanks for the tool, really helpful.

I had a case where /f/o/foo_bar.jpg and /f/o/foo_Bar.jpg were lying around and got an sql constraint vialoation error despite it being two different files that should have been picked up.
I suspect that using utf8 as collation could fix the issue (https://stackoverflow.com/questions/6448825/sql-unique-varchar-case-sensitivity-question) but I have not tested it yet.

**Comment by nealz** [comment]
Had the same issue here and it was fixed by changing the collation.

ALTER TABLE {$this->getTable('fb_imagecleaner_image')}
CHANGE `path` `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;

**Comment by fballiano** [comment]
nice idea @nealz, I'll try to implement it asap

**Comment by fballiano** [comment]
I've released utf8_bin in 1.2.0 ;-) thank you!
