### ISSUE TITLE
Export to CSV/Excel XML

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#4]
![screenshot](https://user-images.githubusercontent.com/8360474/114279075-7153d700-9a3b-11eb-9fa6-f6d00f03363d.jpg)

There are no actions created for this feature (exportCSV, exportExcel). It should be disabled until the actions are created.

**Comment by fballiano** [comment]
export CSV/XLS added, although probably we should hide the "image" column or not render it as HTML (which I don't know if it's possible, in a clean way)

**Comment by fballiano** [comment]
ok, the is_system attribute is right for that:
https://github.com/fballiano/magento1-image-cleaner/commit/d4fca48363598b17f6e2098af6327c58df83de6d
