### ISSUE TITLE
Delete Link

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#5]
![ask_delete](https://user-images.githubusercontent.com/8360474/114296109-fd084a80-9ab1-11eb-9c6d-c7db0729d7cf.jpg)

Please ask the user before deleting an individual image. "Are you sure?". Once someone is pressing Delete the file is gone forever.

**Comment by fballiano** [comment]
fixed, changing the action column got this one out of sight ;-)
