### ISSUE TITLE
Sync grid when there is no directory

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#6]
If any of these do not exist

/media/catalog/folder
/media/catalog/product
/media/wysiwyg

but there are results in grid you should sync the results by removing from database table those related to category/product/wysiwyg. Otherwise you will get errors.

To reproduce this issue go to Magento Backend and fill the grid with results by pressing any of the Sync buttons (e.g. category). Then go to the file system and change the category directory name. Press again [Sync Category Images] button and nothing will change. If you select multiple images or individuals and give any action like Mass Delete, Download, Delete you will get the following errors:

**Mass Delete, Delete:**

```
Warning: unlink(/home/mydomain/public_html/media/catalog/category/adventure-food-1p-brown-bean-soup-pouch.jpg): No such file or directory  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php on line 185

#0 [internal function]: mageCoreErrorHandler(2, 'unlink(/home/mm...', '/home/mydomain/p...', 185, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(185): unlink('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->deleteAction()
#3 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('delete')
#4 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#7 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#8 {main}
```

**Download:**

```
Warning: file_get_contents(/home/mydomain/public_html/media/catalog/category/adventure-food-1p-brown-bean-soup-pouch.jpg): failed to open stream: No such file or directory  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php on line 223

#0 [internal function]: mageCoreErrorHandler(2, 'file_get_conten...', '/home/mydomain/p...', 223, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(223): file_get_contents('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->downloadAction()
#3 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('download')
#4 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#7 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#8 {main}
```

As a fix I see as follows when you click on a Sync button first all records from database tables related to that action (category/product/wysiwyg) should be removed. If the folder exists fill the table with results else show the error message.

**Comment by fballiano** [comment]
Done a few things:
- if an image was removed from FS, the download button throws an error message and removes the entry from DB
- if an image was removed from FS, the delete/massdelete removes the entry from DB without throwing errors
- if it's not possible to remove an image (privileges) the delete/massdelete throws an error message

The thing is, the more "checks" we add the slower it will become (now every files triggers a file_exists before the unlink...) and I don't want this module to be slow just to manage weird situations like "removing the whole folder" which is something I've never seen done.

It would anyway be interesting to be able to check for files manually removed from the FS but still in the DB table, as you say they should be removed and I agree. At the same time I wouldn't want to recheck all files on every sync... it would be easier (and quicker) to just "delete all records for that content_type_id" on every sync (of that same content type), what would you think about that?

**Comment by addison74** [comment]
The only thing I am concern is not generating wired situations when there are missing files or folders. Your approach in bullets is fine to me. 

Let's take the intuitive part of using this extension. When I use it for the first time, the table is empty. I press one of the 3 buttons and I get results. Next time I come back I already have some results. The question is whether they are updated or not? If I use them and they are not updated, problems may occur, the most appropriate would be for the return to this page to lead to an update that I must do to have a picture at this time.

A hard sync versus a soft sync. When I click the [Refresh] button in ImaClean the table is truncated and auto_incremented to 1, then it is filled with records and reflects the situation at that moment. This is a hard sync and it takes around 6 - 7 seconds for 10.000 orphan images on an average system. 

I've been wondering if it wouldn't be easier when I accessed the link in the Tools menu to refresh the table (truncate, auto_increment to 1, find all orphan images catalog/product/wysiwyg). At this point the 3 Sync buttons become usable only when needed. What would be the disadvantage? It would take a few seconds for the grid page to be accessed. If in the meantime unforeseen events happen such as files were accidentally deleted, it was recovered from an older back with a newer database, then those buttons can be used, like a hard sync.

Because it entered my reflex, if I accessed the extension page the first time I would do a hard sync. I would not start working on existing data who knows when it is stored.

**Comment by fballiano** [comment]
I wouldn't do a total refresh on accessing to the mask, because I don't want to trigger thousands of queries and IO on filesystem, unless it's intentional :-)

The idea behind having the data stored on the table was to be able (in the future) to pinpoint some image/file that you never want to delete by mistake (false positives, mostly possible in the WYSIWYG folder) and that could be done only having a new column on the image_cleaner table and keep the data between sessions.

I think it would be a very nice feature (at least for the projects I manage) to have the possibility to say "never delete this image/file" not even if I click the delete button.

We could have "another button" but... nah.. that would be confusing. I don't know, I'll think about that :-D

**Comment by addison74** [comment]
For the moment your extension is a step forward comparing with ImaClean.

**Comment by fballiano** [comment]
I've just pushed the blacklist feature and added a "reset" button to truncate the imagecleaner table (I needed it while testing, less see if we keep it in the future)

**Comment by addison74** [comment]
[Reset] button is very useful and we should keep it. For example if I don't trust the records in grid I can click it and start from scratch for every of category/product/wysiwyg.

PS - I would make a change in the name of the buttons by removing the word "Images" and Reset All.
