### ISSUE TITLE
Improvements to Image Column

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#7]
**First one**
Having a Download link there is no need to keep an <a> tag on image. In this way by clicking on the image we can select the whole row without having an discontinuance.

I suggest in /Block/Adminhtml/Fbimagecleaner/Renderer/Image.php the following change in line 41 from this:

```
return "<a href='{$url}{$row->getPath()}' target='_blank'><img src='{$url}{$row->getPath()}' style='max-width: 200px' /></a>";
```

to

```
return "<img src='{$url}{$row->getPath()}' style='max-width: 200px' />";
```

**Second one**
Remove the filter for this column. It doesn't help since we can do this on the File Name column. In file /Block/Adminhtml/Fbimagecleaner/Grid.php line 70:

```
        $this->addColumn('image', array(
            'header' => $this->__('Image'),
            'type' => 'text',
            'width' => '250px',
            'align'=> 'center',
            'filter'=> false,
            'index' => 'path',
            'sortable' => false,
            'is_system' => true,
            'renderer' => 'Fballiano_ImageCleaner_Block_Adminhtml_Fbimagecleaner_Renderer_Image',
        ));

```

**Comment by fballiano** [comment]
I've removed the filter but I'll keep the link on the image, most of all for people who need to "zoom" to understand what's in the image ;-)
