### ISSUE TITLE
Image Cleaner name

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#8]
I suggest in Tools menu and the grid page the following name from "Image Cleaner" to "Orphan Images Cleaner". It is closer to the purpose of this extension, not giving the impression that it would be a utility for deleting all kind of images.

I did the changes in the following files: 

/etc/adminhtml.xml
/Block/Adminthml/Image.php
/controllers/Adminhtml/FbimagecleanerController.php

**Comment by fballiano** [comment]
I understand but at the same time all the existing modules are called "image clean" or a small variation of that, and I really don't like the "orphaned image cleaner" name sorry!

**Comment by addison74** [comment]
No problem. I appreciate your feedback.
