### ISSUE TITLE
Sync WYSIWYG Button

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#9]
I changed the name for [Sync WYSIWYG] button to [Sync WYSIWYG Images] to keep the same format with the other buttons. It is a harmless change that points only to the artistic impression :)

**Comment by fballiano** [comment]
one day we can clear also files (pdfs ans stuff), not only images so.. mmmm

Il Dom 11 Apr 2021, 09:28 ADDISON ***@***.***> ha scritto:

**Comment by addison74** [comment]
Good. When you will achieve it the extension name should be changed according to Orphan Files Cleaner.

**Comment by addison74** [comment]
I suggest removing the word "Images" from Category and Product buttons. 

[Sync Category] [Sync Product] [Sync WYSIWYG] [Reset]

**Comment by addison74** [comment]
[Reset] button could be changed to [Reset All]
